# Generated by Django 4.2.3 on 2024-02-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstNeme', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phoneNumber', models.IntegerField()),
                ('guestNumber', models.IntegerField()),
                ('day', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('table_number', models.IntegerField(unique=True)),
            ],
        ),
    ]
