# Generated by Django 4.2.3 on 2024-02-19 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_tablebooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablebooking',
            name='phoneNumber',
            field=models.CharField(max_length=10),
        ),
    ]
